# Site settings
title: Statistical Natural Language Processing
subtitle: > # ignore newlines until "description:"
    Course web page, summer semester 2020 -
    <a href="http://www.sfs.uni-tuebingen.de">SfS</a>,
    <a href="http://uni-tuebingen.de/">University of Tübingen</a>
description: > # ignore newlines until "baseurl:"
    This is the course web page for 
    Statistical Natural Language Processing
    taught in the linguistic department (SfS), University of Tübingen.
baseurl: ""
url: "https://snlp2020.github.io"
github_username:  snlp2020
encoding: utf-8
future: true

# Build settings
markdown: kramdown
